# Generated by Django 4.2.13 on 2024-07-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('actors', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moview',
            new_name='Movies',
        ),
    ]
